### ISSUE TITLE
thank you + suggestion

### ISSUE THREAD

**Issue by berteh** [zsiki/bulkvectorexport#4]
just wanted to say thanks. You plugin just saved me 20 minutes manually exporting many layers to KML!

I just wanted to suggest to add a menu entry in the plugin submenu for running it... as I was looking there rather than at a new toolbar.

**Comment by zsiki** [comment]
You are welcome!
In QGIS 3.x plugin has been moved to the vector menu from plugin menu. It is a suggestion from the QGIS developer team. In QGIS 2.x it can be found in the plugin menu.
